In [7]:
print("hello jupyter")

hello jupyter


In [4]:
import numpy as np
Array1 = np.arange(1,20,2) #print the numbers with step 2
Array2 = np.arange(1,21)
print(Array1[2])
print(Array1)
print(Array2)

5
[ 1  3  5  7  9 11 13 15 17 19]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [49]:
x = np.random.rand(2,4) #returns random value from 0 to 1 (2 rows and 2 cols)
print(x)
a1=np.random.randint(10,20,(2,3))
print(a1,a1.max(),a1.argmax())

[[0.82765931 0.08434421 0.57111237 0.47757929]
 [0.79315531 0.18140441 0.85141976 0.41919895]]
[[17 16 15]
 [19 14 14]] 19 3


In [47]:
import numpy as np
arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.array([[[1,2,3],[4,5,6],[2,1,3]]])
arr3 = np.array([12,3,3,4],ndmin=6)
print(arr3,"\n","Arary dimensions-",arr3.ndim )
print(arr1.shape)
print(arr2.shape)

[[[[[[12  3  3  4]]]]]] 
 Arary dimensions- 6
(3, 2)
(1, 3, 3)


In [21]:
import numpy as np
arr1=np.zeros([2,1])
print(arr1)
arr2 = np.full([1,3],4)
print(arr2)
x=np.eye(2,2)
y=np.eye(3)
print(y)
print(x)
print("Data type of arr2:",arr2.dtype)

[[0.]
 [0.]]
[[4 4 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]]
Data type of arr2: int32


In [51]:
import numpy as np
Array1=np.array([1,2,3,4,5])
print(Array1)
Array1[0:2]=0 # reassigned values
print("After reassigning:",Array1)

[1 2 3 4 5]
After reassigning: [0 0 3 4 5]


In [64]:
#slicing in 2D Array
import numpy as np
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1[0,1:3])
print(arr1[1,1:3])
print(arr1[-2,-3:-2])
print(arr1[0,1])

[2 3]
[6 7]
[2]
2


In [49]:
#slicing in 3D array
import numpy as np
arr1=np.array([[[1,2,3],[4,5,6]],[[10,11,12],[6,4,3]]])
print(np.sort(arr1))
reverse=np.flip(arr1)
print(arr1)
print(reverse)
print(arr1[1,0,2])
print(arr1>2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [ 3  4  6]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [ 6  4  3]]]
[[[ 3  4  6]
  [12 11 10]]

 [[ 6  5  4]
  [ 3  2  1]]]
12
[[[False False  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]


In [1]:
#using random.rand()
import numpy as np
arr = np.random.rand(4)
print(arr)


[0.85070214 0.81284176 0.09285762 0.44612914]


In [3]:
#using lambda function
import numpy as np
arr = np.fromfunction(lambda i,j: i==j,(2,2))
print(arr)

[[ True False]
 [False  True]]


In [17]:
#printing iterable variable
import numpy as np
var= (i+i for i in range(5))
itvar=np.fromiter(var,int)
print(itvar)
string=np.fromstring("232 33",sep=' ')
print(string)
arr3=1,2,3,3
arr4=np.matrix(arr3)
print(arr4)

[0 2 4 6 8]
[232.  33.]
[[1 2 3 3]]


In [36]:
import pandas as pd
import numpy as np
arr1 = np.array([[1,2,3,4,23,1,1]])

print(array)
arr1 = pd.DataFrame(arr1)
print(arr1)

[[ 1  2  3  4 23  1  1]]
   0  1  2  3   4  5  6
0  1  2  3  4  23  1  1


In [44]:
import numpy as np
string=np.array(["Ramsha","khan"])
np.char.upper(string)
np.char.title(string)
np.char.lower(string)

array(['ramsha', 'khan'], dtype='<U6')

In [63]:
import numpy as np
arr1 = np.array([1,65,27,13,23,8])
for i in range(5):
    if arr1[i]<6:
        print(i)
#or
np.where(arr1<6)
#to extract data
np.extract(arr1>6,arr1)
#byte swap
arr1.byteswap()

0


array([  16777216, 1090519040,  452984832,  218103808,  385875968,
        134217728])